version: "3.9"

services:
  astr-mongo:
    image: mongo:4.4
    container_name: astr-mongo
    restart: always
    ports:
      - "6545:27017"   # host:container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootasdf
      MONGO_INITDB_DATABASE: astr
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
