version: "3.9"

services:
  astr-mongo:
    image: mongo:4.4
    container_name: astr-mongo
    restart: always
    ports:
      - "6545:27017"   # host:container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-rootasdf}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-astr}
    volumes:
      - mongo_data:/data/db
    networks:
      - astr-network

  astr-app:
    image: ghcr.io/danish-mar/astr:latest
    container_name: astr-app
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      MONGO_URI: ${MONGO_URI:-mongodb://root:rootasdf@astr-mongo:27017/astr?authSource=admin}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRE: ${JWT_EXPIRE:-7d}
      PORT: 3000
    depends_on:
      - astr-mongo
    volumes:
      - ./.wwebjs_auth:/app/.wwebjs_auth
      - ./.wwebjs_cache:/app/.wwebjs_cache
    networks:
      - astr-network

  astr-minio:
    image: minio/minio
    container_name: astr-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-astr_minio_user}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-astr_minio_password}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - astr-network

volumes:
  mongo_data:
  minio_data:

networks:
  astr-network:
    driver: bridge
